### ISSUE TITLE
évolutions de geozones?

### ISSUE THREAD

**Issue by PatGendre** [etalab/geozones#2]
bonjour
bien qu'il soit indiqué "no purpose of universality"...
- est-ce que geozones pourrait évoluer vers un service officiel type BAN, publiant régulièrement les zones des différents territoires administratifs (ou des API, à l'image de http://ou.comarquage.fr/)?
- prévoyez vous d'ajouter les périmètres de transport urbain (https://www.data.gouv.fr/fr/datasets/liste-et-composition-des-ptu/)? 
- avez vous connaissance de projets similaires au niveau européen?
Merci d'avance
cordialement
Patrick Gendre
Cerema Méditerranée

**Comment by noirbizarre** [comment]
Bonjour,

Désolé de répondre si tard.

> est-ce que geozones pourrait évoluer vers un service officiel type BAN, publiant régulièrement les zones des différents territoires administratifs (ou des API, à l'image de http://ou.comarquage.fr/)?

Le jeux de données GeoZones évolue en pour prendre en compte régulièrement les nouveaux découpage administratifs. Ces données sont exposées sur le site data.gouv.fr par certains point d'entrée de l'API non pas dans un soucis d'exposition intégrale mais parce qu'il est nécessaire au fonctionnement de data.gouv.fr. Cette partie a été découplée udata/data.gouv.fr pour être intégrable dans n'importe quel outil si le besoin est là. Il n'est pas exclu par contre que ces données soit intégralement exposées par l'API Carto dont c'est le but.

> prévoyez vous d'ajouter les périmètres de transport urbain (https://www.data.gouv.fr/fr/datasets/liste-et-composition-des-ptu/)?

Non, GeoZones ne contient que des contours administratifs. Les périmètres de transport Urbain correspondent au type de données que l'on peut retrouver dans API Carto par contre.

> avez vous connaissance de projets similaires au niveau européen?

Malheureusement, non. GeoZones a été mis en place après avoir constaté l’inexistence de quelque jeu de données que ce soit sur le sujet. Par contre il a été conçu pour pouvoir fonctionner avec n'importe quel découpage administratif de n'importe quel pays. Nous avons publié la France puisque c'est le périmètre qui nous intéresse mais rien n'empêche de contribuer les découpages d'autres pays, qu'ils soient Européen ou non d'ailleurs.

**Comment by PatGendre** [comment]
bonjour et merci de ce retour,
ce n'était pas urgent et ça reste d'actualité pour moi ! Géozones peut surement avoir des utilisateurs indépendamment de udata.
- est-ce que vous connaissez Territoria? (ou.comarquage.fr, développé au départ par Emmanuel Raviart) C'est très similaire, non? ça pourrait converger?
- en tant que mission Etalab, vous êtes bien placés, si vous pouviez pousser un projet de niveau EU, pour intégrer dans une librairie type geozone les territoires NUTS, ce ne serait pas forcément très compliqué? je pense que cela répondrait aux besoins de beaucoup de gens

Par ailleurs, je travaille en ce moment avec Romain Talès, et un collègue du Cerema, sur l'ouverture des données transport, on a quelques soucis avec la mise à jour de fiches sur data.gouv,  et quelques questions, ce serait possible de s'appeler à ce sujet, ou d'échanger par mail? Merci d'avance

Bien cordialement,
Patrick Gendre

**Comment by noirbizarre** [comment]
Bonjour,

GeoZones est conçu pour être indépendant de udata (d'où le projet séparé).

* Oui, je connais Territoria, Emmanuel Raviart étant l'un de nos collègues.
Le périmètre de territoria et de geozones ne sont pas les mêmes: territoria est une API complète là où GeoZones n'est qu'un jeu de données pouvant être chargé dans n'importe quelle plateforme, Territoria y compris si ça intéresse leur équipe.
GeoZones est beaucoup plus simpliste sur la gestion de la hiérarchie, l'objectif étant avant tout l'autocompletion et l'affichage de contours administratifs, là où l'objectif de Territoria est l'exactitude administrative

* Concernant les NUTS, oui effectivement, GeoZones est conçu pour gérer différents découpage quelques qu'ils soient. Il me semble que les NUTS sont toujours rattachés à un découpage administratif local. Grossièrement, en France, les NUTS2 sont les régions et les NUTS3 les départements. Actuellement nous fournissons le code NUTS associé lorsque nous l'avons. Nous pouvons enrichir les NUTS manquants sur les niveaux qui le nécessitent. Sorti de la France, GeoZones étant prévu pour pouvoir gérer n'importe quel découpage quelque soit le pays, il faut trouver les jeux de données ouvert permettant d'avoir les découpage, avec les NUTS pour les niveaux administratifs qui le necessitent.

Concernant votre problème sur data.gouv.fr, je vous invite à envoyer directemen un mail à moi, mon collègue Romain ou au support data.gouv.fr (info@data.gouv.fr) afin que nous puissions investiguer sur le sujet.

Cordialement,

Axel Haustant

**Comment by PatGendre** [comment]
bonjour et merci de ces compléments,
je comprends mieux comment se comparent territoria et geozones ; les deux ont leur utilité.
Sur l'extension à l'Europe, ce serait surement pertinent pour territoria et pour geozones, avec de nombreux utilisateurs potentiels et aussi de nombreux financeurs potentiels (malheureusement je ne suis pas bien placé pour faire avancer cette idée).
C'est quand même data.gouv.fr qui a référencé les territoires nuts http://nuts.geovocab.org sur le portail http://www.europeandataportal.eu/data/en/dataset/decoupage-nuts-2-des-regions-europeennes, la France est bien placée pour continuer :-)

Je vous contacte par ailleurs concernant data-gouv.
Cordialement,
Patrick Gendre
